mybatis:
  mapper-locations: classpath:/mybatis/*Mapper.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
logging:
  level:
    com.liuhui.shiro.mapper: debug
